// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// libertad_program_create
SEXP libertad_program_create(const Rcpp::List& ir);
RcppExport SEXP _LibeRtAD_libertad_program_create(SEXP irSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type ir(irSEXP);
    rcpp_result_gen = Rcpp::wrap(libertad_program_create(ir));
    return rcpp_result_gen;
END_RCPP
}
// libertad_program_value
Rcpp::NumericVector libertad_program_value(SEXP program_pointer, const Rcpp::NumericVector& at, const Rcpp::CharacterVector& outputs);
RcppExport SEXP _LibeRtAD_libertad_program_value(SEXP program_pointerSEXP, SEXP atSEXP, SEXP outputsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type program_pointer(program_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type at(atSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type outputs(outputsSEXP);
    rcpp_result_gen = Rcpp::wrap(libertad_program_value(program_pointer, at, outputs));
    return rcpp_result_gen;
END_RCPP
}
// libertad_tape_create
SEXP libertad_tape_create(SEXP program_pointer, const Rcpp::NumericVector& at, const Rcpp::CharacterVector& wrt, const Rcpp::CharacterVector& outputs, bool optimize);
RcppExport SEXP _LibeRtAD_libertad_tape_create(SEXP program_pointerSEXP, SEXP atSEXP, SEXP wrtSEXP, SEXP outputsSEXP, SEXP optimizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type program_pointer(program_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type at(atSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type wrt(wrtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type outputs(outputsSEXP);
    Rcpp::traits::input_parameter< bool >::type optimize(optimizeSEXP);
    rcpp_result_gen = Rcpp::wrap(libertad_tape_create(program_pointer, at, wrt, outputs, optimize));
    return rcpp_result_gen;
END_RCPP
}
// libertad_tape_value
Rcpp::NumericVector libertad_tape_value(SEXP tape_pointer, const Rcpp::NumericVector& x);
RcppExport SEXP _LibeRtAD_libertad_tape_value(SEXP tape_pointerSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_pointer(tape_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(libertad_tape_value(tape_pointer, x));
    return rcpp_result_gen;
END_RCPP
}
// libertad_tape_jacobian
Rcpp::NumericMatrix libertad_tape_jacobian(SEXP tape_pointer, const Rcpp::NumericVector& x);
RcppExport SEXP _LibeRtAD_libertad_tape_jacobian(SEXP tape_pointerSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_pointer(tape_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(libertad_tape_jacobian(tape_pointer, x));
    return rcpp_result_gen;
END_RCPP
}
// libertad_tape_hessian
Rcpp::NumericMatrix libertad_tape_hessian(SEXP tape_pointer, const Rcpp::NumericVector& x);
RcppExport SEXP _LibeRtAD_libertad_tape_hessian(SEXP tape_pointerSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_pointer(tape_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(libertad_tape_hessian(tape_pointer, x));
    return rcpp_result_gen;
END_RCPP
}
// libertad_tape_value_gradient
Rcpp::List libertad_tape_value_gradient(SEXP tape_pointer, const Rcpp::NumericVector& x);
RcppExport SEXP _LibeRtAD_libertad_tape_value_gradient(SEXP tape_pointerSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_pointer(tape_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(libertad_tape_value_gradient(tape_pointer, x));
    return rcpp_result_gen;
END_RCPP
}
// libertad_engine_info
Rcpp::List libertad_engine_info();
RcppExport SEXP _LibeRtAD_libertad_engine_info() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(libertad_engine_info());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LibeRtAD_libertad_program_create", (DL_FUNC) &_LibeRtAD_libertad_program_create, 1},
    {"_LibeRtAD_libertad_program_value", (DL_FUNC) &_LibeRtAD_libertad_program_value, 3},
    {"_LibeRtAD_libertad_tape_create", (DL_FUNC) &_LibeRtAD_libertad_tape_create, 5},
    {"_LibeRtAD_libertad_tape_value", (DL_FUNC) &_LibeRtAD_libertad_tape_value, 2},
    {"_LibeRtAD_libertad_tape_jacobian", (DL_FUNC) &_LibeRtAD_libertad_tape_jacobian, 2},
    {"_LibeRtAD_libertad_tape_hessian", (DL_FUNC) &_LibeRtAD_libertad_tape_hessian, 2},
    {"_LibeRtAD_libertad_tape_value_gradient", (DL_FUNC) &_LibeRtAD_libertad_tape_value_gradient, 2},
    {"_LibeRtAD_libertad_engine_info", (DL_FUNC) &_LibeRtAD_libertad_engine_info, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_LibeRtAD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
