// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// reset_ad_node_seq_export
void reset_ad_node_seq_export();
RcppExport SEXP _LibeRtAD_reset_ad_node_seq_export() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    reset_ad_node_seq_export();
    return R_NilValue;
END_RCPP
}
// is_constant_export
bool is_constant_export(SEXP myvar);
RcppExport SEXP _LibeRtAD_is_constant_export(SEXP myvarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type myvar(myvarSEXP);
    rcpp_result_gen = Rcpp::wrap(is_constant_export(myvar));
    return rcpp_result_gen;
END_RCPP
}
// is_variable_export
bool is_variable_export(SEXP myvar);
RcppExport SEXP _LibeRtAD_is_variable_export(SEXP myvarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type myvar(myvarSEXP);
    rcpp_result_gen = Rcpp::wrap(is_variable_export(myvar));
    return rcpp_result_gen;
END_RCPP
}
// add_var
Environment add_var(SEXP e1, SEXP e2);
RcppExport SEXP _LibeRtAD_add_var(SEXP e1SEXP, SEXP e2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type e1(e1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type e2(e2SEXP);
    rcpp_result_gen = Rcpp::wrap(add_var(e1, e2));
    return rcpp_result_gen;
END_RCPP
}
// neg_var
Environment neg_var(SEXP e1);
RcppExport SEXP _LibeRtAD_neg_var(SEXP e1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type e1(e1SEXP);
    rcpp_result_gen = Rcpp::wrap(neg_var(e1));
    return rcpp_result_gen;
END_RCPP
}
// sub_var
Environment sub_var(SEXP e1, SEXP e2);
RcppExport SEXP _LibeRtAD_sub_var(SEXP e1SEXP, SEXP e2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type e1(e1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type e2(e2SEXP);
    rcpp_result_gen = Rcpp::wrap(sub_var(e1, e2));
    return rcpp_result_gen;
END_RCPP
}
// mul_var
Environment mul_var(SEXP e1, SEXP e2);
RcppExport SEXP _LibeRtAD_mul_var(SEXP e1SEXP, SEXP e2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type e1(e1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type e2(e2SEXP);
    rcpp_result_gen = Rcpp::wrap(mul_var(e1, e2));
    return rcpp_result_gen;
END_RCPP
}
// div_var
Environment div_var(SEXP e1, SEXP e2);
RcppExport SEXP _LibeRtAD_div_var(SEXP e1SEXP, SEXP e2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type e1(e1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type e2(e2SEXP);
    rcpp_result_gen = Rcpp::wrap(div_var(e1, e2));
    return rcpp_result_gen;
END_RCPP
}
// pow_var
Environment pow_var(SEXP e1, SEXP e2);
RcppExport SEXP _LibeRtAD_pow_var(SEXP e1SEXP, SEXP e2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type e1(e1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type e2(e2SEXP);
    rcpp_result_gen = Rcpp::wrap(pow_var(e1, e2));
    return rcpp_result_gen;
END_RCPP
}
// sin_var
Environment sin_var(SEXP e1);
RcppExport SEXP _LibeRtAD_sin_var(SEXP e1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type e1(e1SEXP);
    rcpp_result_gen = Rcpp::wrap(sin_var(e1));
    return rcpp_result_gen;
END_RCPP
}
// cos_var
Environment cos_var(SEXP e1);
RcppExport SEXP _LibeRtAD_cos_var(SEXP e1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type e1(e1SEXP);
    rcpp_result_gen = Rcpp::wrap(cos_var(e1));
    return rcpp_result_gen;
END_RCPP
}
// exp_var
Environment exp_var(SEXP e1);
RcppExport SEXP _LibeRtAD_exp_var(SEXP e1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type e1(e1SEXP);
    rcpp_result_gen = Rcpp::wrap(exp_var(e1));
    return rcpp_result_gen;
END_RCPP
}
// log_var
Environment log_var(SEXP e1);
RcppExport SEXP _LibeRtAD_log_var(SEXP e1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type e1(e1SEXP);
    rcpp_result_gen = Rcpp::wrap(log_var(e1));
    return rcpp_result_gen;
END_RCPP
}
// abs_var
Environment abs_var(SEXP e1);
RcppExport SEXP _LibeRtAD_abs_var(SEXP e1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type e1(e1SEXP);
    rcpp_result_gen = Rcpp::wrap(abs_var(e1));
    return rcpp_result_gen;
END_RCPP
}
// sqrt_var
Environment sqrt_var(SEXP e1);
RcppExport SEXP _LibeRtAD_sqrt_var(SEXP e1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type e1(e1SEXP);
    rcpp_result_gen = Rcpp::wrap(sqrt_var(e1));
    return rcpp_result_gen;
END_RCPP
}
// pmax_var
Environment pmax_var(SEXP e1, SEXP e2);
RcppExport SEXP _LibeRtAD_pmax_var(SEXP e1SEXP, SEXP e2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type e1(e1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type e2(e2SEXP);
    rcpp_result_gen = Rcpp::wrap(pmax_var(e1, e2));
    return rcpp_result_gen;
END_RCPP
}
// pmin_var
Environment pmin_var(SEXP e1, SEXP e2);
RcppExport SEXP _LibeRtAD_pmin_var(SEXP e1SEXP, SEXP e2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type e1(e1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type e2(e2SEXP);
    rcpp_result_gen = Rcpp::wrap(pmin_var(e1, e2));
    return rcpp_result_gen;
END_RCPP
}
// sum_var
Environment sum_var(SEXP e1);
RcppExport SEXP _LibeRtAD_sum_var(SEXP e1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type e1(e1SEXP);
    rcpp_result_gen = Rcpp::wrap(sum_var(e1));
    return rcpp_result_gen;
END_RCPP
}
// mean_var
Environment mean_var(SEXP e1);
RcppExport SEXP _LibeRtAD_mean_var(SEXP e1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type e1(e1SEXP);
    rcpp_result_gen = Rcpp::wrap(mean_var(e1));
    return rcpp_result_gen;
END_RCPP
}
// max_var
Environment max_var(SEXP e1);
RcppExport SEXP _LibeRtAD_max_var(SEXP e1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type e1(e1SEXP);
    rcpp_result_gen = Rcpp::wrap(max_var(e1));
    return rcpp_result_gen;
END_RCPP
}
// subset_var
Environment subset_var(SEXP x, int idx);
RcppExport SEXP _LibeRtAD_subset_var(SEXP xSEXP, SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(subset_var(x, idx));
    return rcpp_result_gen;
END_RCPP
}
// matmul_var
Environment matmul_var(SEXP e1, SEXP e2);
RcppExport SEXP _LibeRtAD_matmul_var(SEXP e1SEXP, SEXP e2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type e1(e1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type e2(e2SEXP);
    rcpp_result_gen = Rcpp::wrap(matmul_var(e1, e2));
    return rcpp_result_gen;
END_RCPP
}
// reset_grad_sidecar_cpp
void reset_grad_sidecar_cpp();
RcppExport SEXP _LibeRtAD_reset_grad_sidecar_cpp() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    reset_grad_sidecar_cpp();
    return R_NilValue;
END_RCPP
}
// clear_const_pool_export
void clear_const_pool_export();
RcppExport SEXP _LibeRtAD_clear_const_pool_export() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    clear_const_pool_export();
    return R_NilValue;
END_RCPP
}
// apply_grad_sidecar_cpp
void apply_grad_sidecar_cpp(List tape);
RcppExport SEXP _LibeRtAD_apply_grad_sidecar_cpp(SEXP tapeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type tape(tapeSEXP);
    apply_grad_sidecar_cpp(tape);
    return R_NilValue;
END_RCPP
}
// logsumexp_scalars_var
Environment logsumexp_scalars_var(List terms);
RcppExport SEXP _LibeRtAD_logsumexp_scalars_var(SEXP termsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type terms(termsSEXP);
    rcpp_result_gen = Rcpp::wrap(logsumexp_scalars_var(terms));
    return rcpp_result_gen;
END_RCPP
}
// reverse_diff_node
void reverse_diff_node(Environment myvar);
RcppExport SEXP _LibeRtAD_reverse_diff_node(SEXP myvarSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type myvar(myvarSEXP);
    reverse_diff_node(myvar);
    return R_NilValue;
END_RCPP
}
// reverse_tape_cpp
void reverse_tape_cpp(List tape);
RcppExport SEXP _LibeRtAD_reverse_tape_cpp(SEXP tapeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type tape(tapeSEXP);
    reverse_tape_cpp(tape);
    return R_NilValue;
END_RCPP
}
// reverseDiff
void reverseDiff(Environment myvar);
RcppExport SEXP _LibeRtAD_reverseDiff(SEXP myvarSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type myvar(myvarSEXP);
    reverseDiff(myvar);
    return R_NilValue;
END_RCPP
}
// forwardDiff
double forwardDiff(Environment myvar);
RcppExport SEXP _LibeRtAD_forwardDiff(SEXP myvarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type myvar(myvarSEXP);
    rcpp_result_gen = Rcpp::wrap(forwardDiff(myvar));
    return rcpp_result_gen;
END_RCPP
}
// reset_tape_grads_cpp
void reset_tape_grads_cpp(List tape);
RcppExport SEXP _LibeRtAD_reset_tape_grads_cpp(SEXP tapeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type tape(tapeSEXP);
    reset_tape_grads_cpp(tape);
    return R_NilValue;
END_RCPP
}
// replay_tape_values_cpp
void replay_tape_values_cpp(List tape, List at);
RcppExport SEXP _LibeRtAD_replay_tape_values_cpp(SEXP tapeSEXP, SEXP atSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type tape(tapeSEXP);
    Rcpp::traits::input_parameter< List >::type at(atSEXP);
    replay_tape_values_cpp(tape, at);
    return R_NilValue;
END_RCPP
}
// tape_scalar_value_cpp
double tape_scalar_value_cpp(List tape);
RcppExport SEXP _LibeRtAD_tape_scalar_value_cpp(SEXP tapeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type tape(tapeSEXP);
    rcpp_result_gen = Rcpp::wrap(tape_scalar_value_cpp(tape));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LibeRtAD_reset_ad_node_seq_export", (DL_FUNC) &_LibeRtAD_reset_ad_node_seq_export, 0},
    {"_LibeRtAD_is_constant_export", (DL_FUNC) &_LibeRtAD_is_constant_export, 1},
    {"_LibeRtAD_is_variable_export", (DL_FUNC) &_LibeRtAD_is_variable_export, 1},
    {"_LibeRtAD_add_var", (DL_FUNC) &_LibeRtAD_add_var, 2},
    {"_LibeRtAD_neg_var", (DL_FUNC) &_LibeRtAD_neg_var, 1},
    {"_LibeRtAD_sub_var", (DL_FUNC) &_LibeRtAD_sub_var, 2},
    {"_LibeRtAD_mul_var", (DL_FUNC) &_LibeRtAD_mul_var, 2},
    {"_LibeRtAD_div_var", (DL_FUNC) &_LibeRtAD_div_var, 2},
    {"_LibeRtAD_pow_var", (DL_FUNC) &_LibeRtAD_pow_var, 2},
    {"_LibeRtAD_sin_var", (DL_FUNC) &_LibeRtAD_sin_var, 1},
    {"_LibeRtAD_cos_var", (DL_FUNC) &_LibeRtAD_cos_var, 1},
    {"_LibeRtAD_exp_var", (DL_FUNC) &_LibeRtAD_exp_var, 1},
    {"_LibeRtAD_log_var", (DL_FUNC) &_LibeRtAD_log_var, 1},
    {"_LibeRtAD_abs_var", (DL_FUNC) &_LibeRtAD_abs_var, 1},
    {"_LibeRtAD_sqrt_var", (DL_FUNC) &_LibeRtAD_sqrt_var, 1},
    {"_LibeRtAD_pmax_var", (DL_FUNC) &_LibeRtAD_pmax_var, 2},
    {"_LibeRtAD_pmin_var", (DL_FUNC) &_LibeRtAD_pmin_var, 2},
    {"_LibeRtAD_sum_var", (DL_FUNC) &_LibeRtAD_sum_var, 1},
    {"_LibeRtAD_mean_var", (DL_FUNC) &_LibeRtAD_mean_var, 1},
    {"_LibeRtAD_max_var", (DL_FUNC) &_LibeRtAD_max_var, 1},
    {"_LibeRtAD_subset_var", (DL_FUNC) &_LibeRtAD_subset_var, 2},
    {"_LibeRtAD_matmul_var", (DL_FUNC) &_LibeRtAD_matmul_var, 2},
    {"_LibeRtAD_reset_grad_sidecar_cpp", (DL_FUNC) &_LibeRtAD_reset_grad_sidecar_cpp, 0},
    {"_LibeRtAD_clear_const_pool_export", (DL_FUNC) &_LibeRtAD_clear_const_pool_export, 0},
    {"_LibeRtAD_apply_grad_sidecar_cpp", (DL_FUNC) &_LibeRtAD_apply_grad_sidecar_cpp, 1},
    {"_LibeRtAD_logsumexp_scalars_var", (DL_FUNC) &_LibeRtAD_logsumexp_scalars_var, 1},
    {"_LibeRtAD_reverse_diff_node", (DL_FUNC) &_LibeRtAD_reverse_diff_node, 1},
    {"_LibeRtAD_reverse_tape_cpp", (DL_FUNC) &_LibeRtAD_reverse_tape_cpp, 1},
    {"_LibeRtAD_reverseDiff", (DL_FUNC) &_LibeRtAD_reverseDiff, 1},
    {"_LibeRtAD_forwardDiff", (DL_FUNC) &_LibeRtAD_forwardDiff, 1},
    {"_LibeRtAD_reset_tape_grads_cpp", (DL_FUNC) &_LibeRtAD_reset_tape_grads_cpp, 1},
    {"_LibeRtAD_replay_tape_values_cpp", (DL_FUNC) &_LibeRtAD_replay_tape_values_cpp, 2},
    {"_LibeRtAD_tape_scalar_value_cpp", (DL_FUNC) &_LibeRtAD_tape_scalar_value_cpp, 1},
    {NULL, NULL, 0}
};

void ad_forward_init_c_callables(DllInfo* dll);
void ad_init_c_callables(DllInfo* dll);
RcppExport void R_init_LibeRtAD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    ad_forward_init_c_callables(dll);
    ad_init_c_callables(dll);
}
