// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// libertad_program_create
SEXP libertad_program_create(const Rcpp::List& ir);
RcppExport SEXP _LibeRtAD_libertad_program_create(SEXP irSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type ir(irSEXP);
    rcpp_result_gen = Rcpp::wrap(libertad_program_create(ir));
    return rcpp_result_gen;
END_RCPP
}
// libertad_program_value
Rcpp::NumericVector libertad_program_value(SEXP program_pointer, const Rcpp::NumericVector& at, const Rcpp::CharacterVector& outputs);
RcppExport SEXP _LibeRtAD_libertad_program_value(SEXP program_pointerSEXP, SEXP atSEXP, SEXP outputsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type program_pointer(program_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type at(atSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type outputs(outputsSEXP);
    rcpp_result_gen = Rcpp::wrap(libertad_program_value(program_pointer, at, outputs));
    return rcpp_result_gen;
END_RCPP
}
// libertad_tape_create
SEXP libertad_tape_create(SEXP program_pointer, const Rcpp::NumericVector& at, const Rcpp::CharacterVector& wrt, const Rcpp::CharacterVector& outputs, bool optimize);
RcppExport SEXP _LibeRtAD_libertad_tape_create(SEXP program_pointerSEXP, SEXP atSEXP, SEXP wrtSEXP, SEXP outputsSEXP, SEXP optimizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type program_pointer(program_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type at(atSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type wrt(wrtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type outputs(outputsSEXP);
    Rcpp::traits::input_parameter< bool >::type optimize(optimizeSEXP);
    rcpp_result_gen = Rcpp::wrap(libertad_tape_create(program_pointer, at, wrt, outputs, optimize));
    return rcpp_result_gen;
END_RCPP
}
// libertad_tape_new_dynamic
Rcpp::NumericVector libertad_tape_new_dynamic(SEXP tape_pointer, const Rcpp::NumericVector& values);
RcppExport SEXP _LibeRtAD_libertad_tape_new_dynamic(SEXP tape_pointerSEXP, SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_pointer(tape_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type values(valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(libertad_tape_new_dynamic(tape_pointer, values));
    return rcpp_result_gen;
END_RCPP
}
// libertad_tape_info
Rcpp::List libertad_tape_info(SEXP tape_pointer);
RcppExport SEXP _LibeRtAD_libertad_tape_info(SEXP tape_pointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_pointer(tape_pointerSEXP);
    rcpp_result_gen = Rcpp::wrap(libertad_tape_info(tape_pointer));
    return rcpp_result_gen;
END_RCPP
}
// libertad_tape_graph_json
std::string libertad_tape_graph_json(SEXP tape_pointer);
RcppExport SEXP _LibeRtAD_libertad_tape_graph_json(SEXP tape_pointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_pointer(tape_pointerSEXP);
    rcpp_result_gen = Rcpp::wrap(libertad_tape_graph_json(tape_pointer));
    return rcpp_result_gen;
END_RCPP
}
// libertad_tape_from_graph_json
SEXP libertad_tape_from_graph_json(SEXP program_pointer, const std::string& graph_json, const Rcpp::CharacterVector& domain, const Rcpp::CharacterVector& dynamic, const Rcpp::NumericVector& dynamic_values, const Rcpp::CharacterVector& range);
RcppExport SEXP _LibeRtAD_libertad_tape_from_graph_json(SEXP program_pointerSEXP, SEXP graph_jsonSEXP, SEXP domainSEXP, SEXP dynamicSEXP, SEXP dynamic_valuesSEXP, SEXP rangeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type program_pointer(program_pointerSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type graph_json(graph_jsonSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type domain(domainSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type dynamic(dynamicSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type dynamic_values(dynamic_valuesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type range(rangeSEXP);
    rcpp_result_gen = Rcpp::wrap(libertad_tape_from_graph_json(program_pointer, graph_json, domain, dynamic, dynamic_values, range));
    return rcpp_result_gen;
END_RCPP
}
// libertad_tape_value
Rcpp::NumericVector libertad_tape_value(SEXP tape_pointer, const Rcpp::NumericVector& x);
RcppExport SEXP _LibeRtAD_libertad_tape_value(SEXP tape_pointerSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_pointer(tape_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(libertad_tape_value(tape_pointer, x));
    return rcpp_result_gen;
END_RCPP
}
// libertad_tape_jacobian
Rcpp::NumericMatrix libertad_tape_jacobian(SEXP tape_pointer, const Rcpp::NumericVector& x);
RcppExport SEXP _LibeRtAD_libertad_tape_jacobian(SEXP tape_pointerSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_pointer(tape_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(libertad_tape_jacobian(tape_pointer, x));
    return rcpp_result_gen;
END_RCPP
}
// libertad_tape_hessian
Rcpp::NumericMatrix libertad_tape_hessian(SEXP tape_pointer, const Rcpp::NumericVector& x);
RcppExport SEXP _LibeRtAD_libertad_tape_hessian(SEXP tape_pointerSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_pointer(tape_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(libertad_tape_hessian(tape_pointer, x));
    return rcpp_result_gen;
END_RCPP
}
// libertad_tape_value_gradient
Rcpp::List libertad_tape_value_gradient(SEXP tape_pointer, const Rcpp::NumericVector& x);
RcppExport SEXP _LibeRtAD_libertad_tape_value_gradient(SEXP tape_pointerSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_pointer(tape_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(libertad_tape_value_gradient(tape_pointer, x));
    return rcpp_result_gen;
END_RCPP
}
// libertad_gauss_hermite_grid
Rcpp::List libertad_gauss_hermite_grid(int order, int dimension, double max_points);
RcppExport SEXP _LibeRtAD_libertad_gauss_hermite_grid(SEXP orderSEXP, SEXP dimensionSEXP, SEXP max_pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    Rcpp::traits::input_parameter< int >::type dimension(dimensionSEXP);
    Rcpp::traits::input_parameter< double >::type max_points(max_pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(libertad_gauss_hermite_grid(order, dimension, max_points));
    return rcpp_result_gen;
END_RCPP
}
// libertad_smolyak_gauss_hermite_grid
Rcpp::List libertad_smolyak_gauss_hermite_grid(int level, int dimension, double max_points);
RcppExport SEXP _LibeRtAD_libertad_smolyak_gauss_hermite_grid(SEXP levelSEXP, SEXP dimensionSEXP, SEXP max_pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type level(levelSEXP);
    Rcpp::traits::input_parameter< int >::type dimension(dimensionSEXP);
    Rcpp::traits::input_parameter< double >::type max_points(max_pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(libertad_smolyak_gauss_hermite_grid(level, dimension, max_points));
    return rcpp_result_gen;
END_RCPP
}
// libertad_checkpoint_probe
Rcpp::List libertad_checkpoint_probe(int repetitions, int evaluations);
RcppExport SEXP _LibeRtAD_libertad_checkpoint_probe(SEXP repetitionsSEXP, SEXP evaluationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type repetitions(repetitionsSEXP);
    Rcpp::traits::input_parameter< int >::type evaluations(evaluationsSEXP);
    rcpp_result_gen = Rcpp::wrap(libertad_checkpoint_probe(repetitions, evaluations));
    return rcpp_result_gen;
END_RCPP
}
// libertad_engine_info
Rcpp::List libertad_engine_info();
RcppExport SEXP _LibeRtAD_libertad_engine_info() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(libertad_engine_info());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LibeRtAD_libertad_program_create", (DL_FUNC) &_LibeRtAD_libertad_program_create, 1},
    {"_LibeRtAD_libertad_program_value", (DL_FUNC) &_LibeRtAD_libertad_program_value, 3},
    {"_LibeRtAD_libertad_tape_create", (DL_FUNC) &_LibeRtAD_libertad_tape_create, 5},
    {"_LibeRtAD_libertad_tape_new_dynamic", (DL_FUNC) &_LibeRtAD_libertad_tape_new_dynamic, 2},
    {"_LibeRtAD_libertad_tape_info", (DL_FUNC) &_LibeRtAD_libertad_tape_info, 1},
    {"_LibeRtAD_libertad_tape_graph_json", (DL_FUNC) &_LibeRtAD_libertad_tape_graph_json, 1},
    {"_LibeRtAD_libertad_tape_from_graph_json", (DL_FUNC) &_LibeRtAD_libertad_tape_from_graph_json, 6},
    {"_LibeRtAD_libertad_tape_value", (DL_FUNC) &_LibeRtAD_libertad_tape_value, 2},
    {"_LibeRtAD_libertad_tape_jacobian", (DL_FUNC) &_LibeRtAD_libertad_tape_jacobian, 2},
    {"_LibeRtAD_libertad_tape_hessian", (DL_FUNC) &_LibeRtAD_libertad_tape_hessian, 2},
    {"_LibeRtAD_libertad_tape_value_gradient", (DL_FUNC) &_LibeRtAD_libertad_tape_value_gradient, 2},
    {"_LibeRtAD_libertad_gauss_hermite_grid", (DL_FUNC) &_LibeRtAD_libertad_gauss_hermite_grid, 3},
    {"_LibeRtAD_libertad_smolyak_gauss_hermite_grid", (DL_FUNC) &_LibeRtAD_libertad_smolyak_gauss_hermite_grid, 3},
    {"_LibeRtAD_libertad_checkpoint_probe", (DL_FUNC) &_LibeRtAD_libertad_checkpoint_probe, 2},
    {"_LibeRtAD_libertad_engine_info", (DL_FUNC) &_LibeRtAD_libertad_engine_info, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_LibeRtAD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
