.ad_gui_rows <- function(values) {
  if (is.null(values) || !length(values)) return(list())
  if (is.data.frame(values)) {
    return(unname(lapply(seq_len(nrow(values)), function(index) as.list(values[index, , drop = FALSE]))))
  }
  unname(lapply(values, as.list))
}

.ad_gui_payload <- function(result = NULL, ecosystem = NULL, ecosystem_log = character(),
                            benchmark_script = NULL,
                            ecosystem_running = FALSE,
                            status = list(level = "info", text = "Benchmark laboratory ready"),
                            icon = NULL) {
  engine <- ad_engine_info()
  list(
    cases = .ad_gui_rows(ad_benchmark_cases()),
    engine = unname(as.list(engine)), engineNamed = as.list(engine),
    native = if (is.null(result)) NULL else list(
      case = result$case, label = result$label, description = result$description,
      timings = .ad_gui_rows(result$timings), accuracy = .ad_gui_rows(result$accuracy),
      settings = result$settings, generatedAt = result$generated_at
    ),
    ecosystem = ecosystem,
    ecosystemLog = as.character(ecosystem_log),
    benchmarkAvailable = !is.null(benchmark_script) && file.exists(benchmark_script),
    benchmarkScript = benchmark_script,
    ecosystemRunning = isTRUE(ecosystem_running),
    defaultOutput = .ad_default_benchmark_output(),
    status = status, icon = icon,
    packageVersion = tryCatch(as.character(utils::packageVersion("LibeRtAD")),
                              error = function(error) "0.7.3")
  )
}

#' LibeRtAD benchmark workbench widget
#' @param payload Workbench payload generated by [libertad_gui()].
#' @param input_id Shiny event prefix.
#' @param width,height Widget dimensions.
#' @param elementId Optional widget element id.
#' @export
libertad_workbench <- function(payload, input_id = "libertad_workbench",
                               width = NULL, height = "100vh", elementId = NULL) {
  content <- reactR::component("LibeRtADWorkbench", c(payload, list(inputId = input_id)))
  htmlwidgets::createWidget(
    name = "libertadWorkbench", reactR::reactMarkup(content), width = width,
    height = height, package = "LibeRtAD", elementId = elementId
  )
}

#' @noRd
widget_html.libertadWorkbench <- function(id, style, class, ...) {
  htmltools::attachDependencies(
    htmltools::tags$div(id = id, class = class, style = style),
    list(reactR::html_dependency_corejs(), reactR::html_dependency_react(),
         reactR::html_dependency_reacttools())
  )
}

#' Shiny output for the LibeRtAD workbench
#' @param outputId Output id.
#' @param width,height CSS dimensions.
#' @export
libertadWorkbenchOutput <- function(outputId, width = "100%", height = "100vh") {
  htmlwidgets::shinyWidgetOutput(outputId, "libertadWorkbench", width, height,
                                 package = "LibeRtAD")
}

#' Render a LibeRtAD workbench
#' @param expr Widget expression.
#' @param env Evaluation environment.
#' @param quoted Whether expression is quoted.
#' @export
renderLibertadWorkbench <- function(expr, env = parent.frame(), quoted = FALSE) {
  if (!quoted) expr <- substitute(expr)
  htmlwidgets::shinyRenderWidget(expr, libertadWorkbenchOutput, env, quoted = TRUE)
}
