# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

reset_ad_node_seq_cpp <- function() {
    invisible(.Call(`_LibeRtAD_reset_ad_node_seq_export`))
}

is_constant_cpp <- function(myvar) {
    .Call(`_LibeRtAD_is_constant_export`, myvar)
}

is_variable_cpp <- function(myvar) {
    .Call(`_LibeRtAD_is_variable_export`, myvar)
}

add_var <- function(e1, e2) {
    .Call(`_LibeRtAD_add_var`, e1, e2)
}

neg_var <- function(e1) {
    .Call(`_LibeRtAD_neg_var`, e1)
}

sub_var <- function(e1, e2) {
    .Call(`_LibeRtAD_sub_var`, e1, e2)
}

mul_var <- function(e1, e2) {
    .Call(`_LibeRtAD_mul_var`, e1, e2)
}

div_var <- function(e1, e2) {
    .Call(`_LibeRtAD_div_var`, e1, e2)
}

pow_var <- function(e1, e2) {
    .Call(`_LibeRtAD_pow_var`, e1, e2)
}

sin_var <- function(e1) {
    .Call(`_LibeRtAD_sin_var`, e1)
}

cos_var <- function(e1) {
    .Call(`_LibeRtAD_cos_var`, e1)
}

exp_var <- function(e1) {
    .Call(`_LibeRtAD_exp_var`, e1)
}

log_var <- function(e1) {
    .Call(`_LibeRtAD_log_var`, e1)
}

abs_var <- function(e1) {
    .Call(`_LibeRtAD_abs_var`, e1)
}

sqrt_var <- function(e1) {
    .Call(`_LibeRtAD_sqrt_var`, e1)
}

pmax_var <- function(e1, e2) {
    .Call(`_LibeRtAD_pmax_var`, e1, e2)
}

pmin_var <- function(e1, e2) {
    .Call(`_LibeRtAD_pmin_var`, e1, e2)
}

sum_var <- function(e1) {
    .Call(`_LibeRtAD_sum_var`, e1)
}

mean_var <- function(e1) {
    .Call(`_LibeRtAD_mean_var`, e1)
}

max_var <- function(e1) {
    .Call(`_LibeRtAD_max_var`, e1)
}

subset_var <- function(x, idx) {
    .Call(`_LibeRtAD_subset_var`, x, idx)
}

matmul_var <- function(e1, e2) {
    .Call(`_LibeRtAD_matmul_var`, e1, e2)
}

reset_grad_sidecar_cpp <- function() {
    invisible(.Call(`_LibeRtAD_reset_grad_sidecar_cpp`))
}

clear_const_pool_export <- function() {
    invisible(.Call(`_LibeRtAD_clear_const_pool_export`))
}

apply_grad_sidecar_cpp <- function(tape) {
    invisible(.Call(`_LibeRtAD_apply_grad_sidecar_cpp`, tape))
}

logsumexp_scalars_var <- function(terms) {
    .Call(`_LibeRtAD_logsumexp_scalars_var`, terms)
}

reverse_diff_node <- function(myvar) {
    invisible(.Call(`_LibeRtAD_reverse_diff_node`, myvar))
}

reverse_tape_cpp <- function(tape) {
    invisible(.Call(`_LibeRtAD_reverse_tape_cpp`, tape))
}

reverseDiff <- function(myvar) {
    invisible(.Call(`_LibeRtAD_reverseDiff`, myvar))
}

forwardDiff <- function(myvar) {
    .Call(`_LibeRtAD_forwardDiff`, myvar)
}

reset_tape_grads_cpp <- function(tape) {
    invisible(.Call(`_LibeRtAD_reset_tape_grads_cpp`, tape))
}

replay_tape_values_cpp <- function(tape, at) {
    invisible(.Call(`_LibeRtAD_replay_tape_values_cpp`, tape, at))
}

tape_scalar_value_cpp <- function(tape) {
    .Call(`_LibeRtAD_tape_scalar_value_cpp`, tape)
}

