# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.libertad_program_create <- function(ir) {
    .Call(`_LibeRtAD_libertad_program_create`, ir)
}

.libertad_program_value <- function(program_pointer, at, outputs) {
    .Call(`_LibeRtAD_libertad_program_value`, program_pointer, at, outputs)
}

.libertad_tape_create <- function(program_pointer, at, wrt, outputs, optimize = TRUE) {
    .Call(`_LibeRtAD_libertad_tape_create`, program_pointer, at, wrt, outputs, optimize)
}

.libertad_tape_value <- function(tape_pointer, x) {
    .Call(`_LibeRtAD_libertad_tape_value`, tape_pointer, x)
}

.libertad_tape_jacobian <- function(tape_pointer, x) {
    .Call(`_LibeRtAD_libertad_tape_jacobian`, tape_pointer, x)
}

.libertad_tape_hessian <- function(tape_pointer, x) {
    .Call(`_LibeRtAD_libertad_tape_hessian`, tape_pointer, x)
}

.libertad_tape_value_gradient <- function(tape_pointer, x) {
    .Call(`_LibeRtAD_libertad_tape_value_gradient`, tape_pointer, x)
}

.libertad_engine_info <- function() {
    .Call(`_LibeRtAD_libertad_engine_info`)
}

